### ISSUE TITLE
Failed to f etch plugin https://github.com/vstirbu/PromisesPlugin.git via registry.

### ISSUE THREAD

**Issue by madhuvarrier** [vstirbu/PromisesPlugin#10]
Any idea about the error below?
Unsure why looking for git locally?

Thanks
Madhu Varrier

Failed to install 'cordova-plugin-screen-orientation': CordovaError: Failed to f
etch plugin https://github.com/vstirbu/PromisesPlugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by vstirbu** [comment]
Seems similar to #6.

**Comment by madhuvarrier** [comment]
Tried random attempts and when attempted in console with admin privileges, it worked. Did not do anything changing dependency part. Will try your suggestion if this happens again. Thank you
