### ISSUE TITLE
Minified 

### ISSUE THREAD

**Issue by purplecabbage** [vstirbu/PromisesPlugin#2]
Your minified code is unreadable.  I would like to know if you check if window.Promise is already defined, but I can't tell.

**Comment by vstirbu** [comment]
The plugin [auto-polyfills](https://github.com/jakearchibald/es6-promise#auto-polyfill) the global object, which [seems](https://github.com/jakearchibald/es6-promise/blob/master/dist/es6-promise.js#L931) to check if there is already a `Promise` in place.

**Comment by purplecabbage** [comment]
[this](https://github.com/vstirbu/PromisesPlugin/blob/master/plugin.xml#L20) May overwrite the global window object regardless.

**Comment by vstirbu** [comment]
Oh, good catch! So if that line is removed it should be safe, right?

**Comment by purplecabbage** [comment]
I am not 100%, you will have to try things out.
Presumably, the polyfil will do something like :

`if (window.Promise) {
  module.exports = window.Promise;
}
else ...
`

In which case it would be fine ...
plugin.xml also supports 'merges' which is designed to just add methods and
properties to an existing object.
And it supports the 'runs' tag which may be best suited for your needs,
simply runs some javascript code, which presumably does it's own assigning
to window.Promise if need be.
