### ISSUE TITLE
Result is undefined when innerResolve() is called

### ISSUE THREAD

**Issue by ovidiugabriel** [vstirbu/PromisesPlugin#4]
Hello,

I have a strange problem while running this plugin in Cordova. Result is undefined when innerResolve() is called from Channel.fire (cordova.js).

What I've done wrong?

``` javascript
ready: new Promise(function(resolve, reject) {
    var innerResolve = function(result) {  // <<--- here result is undefined
        var onDeviceReady = function() {
            resolve(new ServiceWorkerRegistration(result.installing, result.waiting, 
                new ServiceWorker(), result.registeringScriptUrl, result.scope));
        }
        document.addEventListener('deviceready', onDeviceReady, false); 
    }
    exec(innerResolve, null, "ServiceWorker", "serviceWorkerReady", []);
}),
```

**Comment by vstirbu** [comment]
Hi,

The snippet looks fine at first glance. `innerResolve` is invoked by the plugin but the result is not the expected one. Could it be that the plugin itself has not installed properly? Can you make a inimal app that can reproduce the issue?

**Comment by vstirbu** [comment]
any update on this?

**Comment by ovidiugabriel** [comment]
We can close it. It seems to me that Service Workers are not a mature technology yet.
I will postpone its adoption. Thanks!
