### ISSUE TITLE
Problem related with plugin signature

### ISSUE THREAD

**Issue by ScorpionXII** [vstirbu/PromisesPlugin#5]
I'm having this problem since few days, I think there it's something related with the default called signature, because I just made the same request including @2.3.0 version at the end and the install was OK

> cordova plugin add es6-promise-plugin --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add es6-promise-plugin --save (exit code 1):

        Error: Failed to fetch plugin git+https://github.com/vstirbu/PromisesPlugin.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module

**Comment by vstirbu** [comment]
Are you installing the plugin directly or as a dependency in another plugin? What is the exact command that you run from command prompt?

**Comment by ScorpionXII** [comment]
This command:
cordova plugin add es6-promise-plugin (Error!)

This one:
cordova plugin add es6-promise-plugin@2.3.0 (OK!)

**Comment by vstirbu** [comment]
I can run:

```
cordova plugin add es6-promise-plugin@2.3.0
```

or 

```
cordova plugin add es6-promise-plugin
```

without problems here.

Not a user of ionic lately but not so sure if you can just run cordova in a ionic project just like that.

Do you have an older version of the plugin or some other plugin that relies on this one? You might need to remove those before you can do anything.

A bad smell about your project/environment is that cordova tries to install this plugin from github instead of npm:

> Error: Failed to fetch plugin git+https://github.com/vstirbu/PromisesPlugin.git via registry.

**Comment by ScorpionXII** [comment]
The plugin its also loaded as dependency of cordova-plugin-screen-orientation, I dont know why the default reference it's from Github!

**Comment by vstirbu** [comment]
Ok. it is because of this: https://github.com/apache/cordova-plugin-screen-orientation/blob/master/plugin.xml#L55. I'll get in touch with the maintainers of that one to remove the dependency but that might take a while.

Do you need the the plugin directly in your project?

**Comment by vstirbu** [comment]
seems that there is already a pull request opened there but it has not been merged: https://github.com/apache/cordova-plugin-screen-orientation/pull/15

**Comment by ScorpionXII** [comment]
Oh!, yes I need it, but I can solve the problem installing it with forced
version. Sorry if I opened the issue thread and it's not directly related
with your plugin!

But thanks a lot for your quick answer and support!

**Comment by vstirbu** [comment]
Actually it is good that you opened it as the documentation is outdated. I have to update the `dependency` example so that the plugin is pulled from npm. Thanks!

**Comment by vstirbu** [comment]
You could give a +1 on that pull request to (maybe) speed up things. I've done that! :D
