### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by ccravens** [vstirbu/PromisesPlugin#6]
When trying to add / remove platforms and plugins from my ionic project, I keep getting this error:

```
Error: Failed to fetch platform cordova-android@^6.2.3
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 194 Error output:
npm ERR! path /Users/ccravens/Business/ossys/Clients/SES/src/ses-ionic/node_modules/es6-promise-plugin/package.json
npm ERR! code ELOOP
npm ERR! errno -62
npm ERR! syscall open
npm ERR! ELOOP: too many symbolic links encountered, open '/Users/ccravens/Business/ossys/Clients/SES/src/ses-ionic/node_modules/es6-promise-plugin/package.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ccravens/.npm/_logs/2017-07-12T19_12_55_391Z-debug.log

```
I noticed that it seems when ionic installs es6-promise-plugin, it creates a symbolic link to itself?

`8 lrwxr-xr-x    1 ccravens  staff     18 Jul 12 15:09 es6-promise-plugin -> es6-promise-plugin`

**Comment by vstirbu** [comment]
Can you share more about your environment, at least the ionic version. Thanks!

**Comment by ccravens** [comment]
This may be due to local configuration I am working on.

I'm trying to add a custom plugin to my ionic project and everytime I try to add or remove a platform I get an entry in my package.json like this:

`"es6-promise-plugin": "file:node_modules/es6-promise-plugin"`

**Comment by ccravens** [comment]
```
$ ionic --version
2.2.2
```

**Comment by vstirbu** [comment]
have you installed yourself the plugin or it is a dependency of another plugin? at least the official screen orientation plugin uses uses it.

**Comment by ccravens** [comment]
It's a dependency of another plugin I believe. I think it's due to local configuration issues and very strange / unexpected behavior of ionic adding dependencies for me and somehow referencing itself? I don't think it's an issue with this plugin specifically. At first I thought it might have been an issue with the npm registry configuration for this plugin.

**Comment by vstirbu** [comment]
try to find out which one it doing it. there might be an issue with the way it declares the dependency. it needs to be in this format:

```
<dependency id="es6-promise-plugin" version="4.1.0" />
```

not referencing the repo on github.

**Comment by ccravens** [comment]
After continuing to deal with ionic build issues I was getting this error:

```
Error: Failed to fetch plugin https://github.com/ossys/cordova-plugin-ble-central via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "es6-promise-plugin" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ccravens/.npm/_logs/2017-07-12T20_20_40_332Z-debug.log
```

I removed the package-lock.json file and it seems to allow me to add plugins again.

I think that package-lock.json file (new npm feature) has caused us a lot of issues recently. I'll update if I learn more but removing this file seemed to help for now.

**Comment by vstirbu** [comment]
Right, npm 5 might be too new for ionic 2 :)

**Comment by ccravens** [comment]
Yah I really appreciate your response. I think we can mark this issue as closed, as I'm not sure if there's any updates we can make to this plugin specifically to resolve this issue. Just one of those forehead-smacking moments. Thanks!

**Comment by ccravens** [comment]
Another note, after further investigation it looks like it was a dependency from this plugin:

`cordova-plugin-x-socialsharing`

and this is the entry in the plugins.xml file for that plugin:

`./plugins/cordova-plugin-x-socialsharing/plugin.xml:28:  <dependency id="es6-promise-plugin"/>`

```
# grep -rni "es6-promise-plugin" .
./node_modules/cordova-plugin-x-socialsharing/plugin.xml:28:  <dependency id="es6-promise-plugin"/>
grep: ./node_modules/npmlog/node_modules/.bin/supports-color: No such file or directory
./package.json:36:        "es6-promise-plugin": "file:node_modules/es6-promise-plugin",
./plugins/cordova-plugin-x-socialsharing/plugin.xml:28:  <dependency id="es6-promise-plugin"/>
```

**Comment by imsushree** [comment]
Hi There,
I am using cordova-plugin-screen-orientation plugin for my application. 
Ionic version : 3.9.2
Cordova version : 7.0.1
Its seems to have a dependency on es6-promise-plugin. And its automatically referencing to the git repo. I am getting connection errors, while I do have an active internet connection. I tried adding "^4.1.0" in place of the git+url, removed the plugin, added once again. Still its automatically referencing to the repo and causing errors. Removed package-lock.json still no luck.
Thanks in advance.

**Comment by vstirbu** [comment]
Are you using the latest `cordova-plugin-screen-orientation` version?

**Comment by brunobastosg** [comment]
I have the same problem when using [this plugin](https://github.com/dickverweij/nl-afas-cordova-plugin-securelocalstorage). I noticed it was referencing the repo on GitHub, so I [forked it](https://github.com/brunobastosg/nl-afas-cordova-plugin-securelocalstorage) to use the proper syntax. But I still keep getting this error:

```
Installing "nl-afas-cordova-plugin-securelocalstorage" for android
Failed to install 'nl-afas-cordova-plugin-securelocalstorage': CordovaError: Failed to fetch plugin es6-promise-plugin@4.2.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

Here are some information about my environment:

```
cli packages:

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.2.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.9.5
    npm               : 5.6.0 
    OS                : Linux 4.4
```

Any tips on what I should try next?

**Comment by vstirbu** [comment]
Would have to replace the [dependency](https://github.com/brunobastosg/nl-afas-cordova-plugin-securelocalstorage/blob/2ded7cd093a34e59befebc79da9b18ccd3bee62b/plugin.xml#L8) in your fork to this format:

```
<dependency id="es6-promise-plugin" version="4.2.2" />
```

Also, you might have uninstall the old version, check that everything is clean and install your fork...
